# Generated by Django 4.2.6 on 2023-11-05 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('quantity', models.IntegerField()),
                ('costPerUnit', models.FloatField()),
                ('dateFilled', models.DateField()),
                ('category', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('salesPrice', models.FloatField(default=0)),
            ],
        ),
    ]
