# Generated by Django 4.2.6 on 2023-10-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('costPerUnit', models.IntegerField()),
                ('dateFilled', models.DateField()),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
