# Generated by Django 4.2.6 on 2023-10-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='id',
        ),
        migrations.AddField(
            model_name='inventory',
            name='category',
            field=models.CharField(default='test_category', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventory',
            name='description',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
