POST http://127.0.0.1:8000/user/create_account 
Content-Type: application/json

{"password": "password", "email": "admin@admin.com", "is_superuser": true }

### Creates admin account

POST http://127.0.0.1:8000/user/create_account 
Content-Type: application/json

{"password": "password", "email": "user@user.com"}

### Creates user account

POST http://127.0.0.1:8000/user/create_account 
Content-Type: application/json

{"password": "password", "email": "drone@drone.com", "is_staff": true}

### Creates drone owner account

POST http://127.0.0.1:8000/user/login 
Content-Type: application/json

{ "email": "adam@mail.com", "password": "Pass1234!" }

###

GET http://127.0.0.1:8000/user/test_token 
Content-Type: application/json
Authorization: Token b0d5dac5a3f4c8c0bcc8d1740d1759c86b10ca27

###

DELETE http://127.0.0.1:8000/user/delete_account
Content-Type: application/json
Authorization: Token b0d5dac5a3f4c8c0bcc8d1740d1759c86b10ca27

{ "email": "adam@mail.com" }