# Generated by Django 4.2.6 on 2023-11-07 16:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cone', models.CharField(max_length=25)),
                ('iceCream', models.CharField(max_length=25)),
                ('toppings', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), size=None)),
                ('cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField()),
                ('droneID', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('cones', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('location', models.CharField(max_length=200)),
                ('timeOrdered', models.DateTimeField()),
                ('timeDelivered', models.DateTimeField(null=True)),
            ],
        ),
    ]
